### ISSUE TITLE
Remixd Rejects Connections

### ISSUE THREAD

**Issue by 13r0ck** [ethereum/remixd#110]
## My Issue
I am unable to connect Remix-IDE with my local files. In my computer's terminal I get the following error for both http and https when trying to Activate the Remixd plugin.
> Connection from origin http://remix.ethereum.org rejected.
> Connection from origin https://remix.ethereum.org rejected.

The Remix-IDE throws the error:
> Cannot connect to the remixd daemon.Please make sure you have the remixd running in the background.

## Extra Info
- Linux: Fedora 32
- I get the issue in both Brave and Firefox
- I just made a clean global install of remixd `npm install -g remixd`
- I am using the command:
```remixd -s <absolute-path-to-the-shared-folder> --remix-ide <your-remix-ide-URL-instance>```
- For `<your-remix-ide-URL-instace>` I have tried:
> https://remix.etherium.org
> htttp://remix.etherium.org
> https://localhost:8080
> http://localhost:8080
> localhost:8080
> localhost
- I have tried running the remix-ide in `https://remix.etherium.org`, `http://remix.etherium.org`, and `https://https://remix.ethereum.org/#optimize=false`

_____________________________________________________________________________

I am not sure what else to do from here. **Thank you!**

**Comment by petscheit** [comment]
+1

**Comment by yann300** [comment]
and have you tried `--remix-ide https://remix.ethereum.org`

**Comment by yann300** [comment]
also as an alternative you can also install https://github.com/ethereum/remix-desktop/releases

**Comment by petscheit** [comment]
Oddly this runs perfectly now, couldn't get it to work yesterday. 
Also wasn't aware there is a desktop build, probably will use that from now on. Thanks for pointing me in that direction!

**Comment by 13r0ck** [comment]
I just moved over to developing with Truffle.
