### ISSUE TITLE
'undefined'

### ISSUE THREAD

**Issue by yann300** [ethereum/remixd#4]
Sometimes the content of a file is replaced by 'undefined'

**Comment by p-s-dev** [comment]
Seeing this also.  Version remixd@0.1.8-alpha.4.  Running remixd while switching between editing in remix browser, and IntelliJ IDE, and git committing and pushing.

Error prinnted to remixd console:
`trying to write "undefined" ! stopping.`

**Comment by jakkyo** [comment]
Got same error.
Windows 10. Visual Code editor

**Comment by yann300** [comment]
please could you try upgrading remixd? try 0.1.8-alpha.5
also which remix-ide are you using?
