### ISSUE TITLE
Remixd fails to Install OSX "missing package name"

### ISSUE THREAD

**Issue by crazyrabbitLTC** [ethereum/remixd#41]
I'm not able to install Remixd on my dev OSX laptop. 

I have web3 0.20.0 working, so not sure what the problem is. 

The error I'm getting is: 
20 error Can't install /usr/local/lib/node_modules/remixd/node_modules/web3/packages/web3-eth-abi: Missing package name

Full error log is: 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.7.1_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v9.7.1
4 verbose npm-session d0ee562c3267c64c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 info lifecycle @~prepack: @
8 info lifecycle @~postpack: @
9 silly pacote directory manifest for undefined@file: fetched in 302ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 verbose stack Error: Can't install /usr/local/lib/node_modules/remixd/node_modules/web3/packages/web3-eth-abi: Missing package name
14 verbose stack     at hasMinimumFields (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:26:15)
14 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
14 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
14 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
14 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
14 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:3)
14 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
14 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
14 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
14 verbose stack     at Installer.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/install.js:477:3)
14 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
15 verbose cwd /usr/local/lib/node_modules/remixd/node_modules/web3/packages/web3-eth-abi
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/Cellar/node/9.7.1_1/bin/node" "/usr/local/bin/npm" "install"
18 verbose node v9.7.1
19 verbose npm  v5.6.0
20 error Can't install /usr/local/lib/node_modules/remixd/node_modules/web3/packages/web3-eth-abi: Missing package name
21 verbose exit [ 1, true ]

**Comment by yann300** [comment]
could be related to https://github.com/ethereum/remixd/issues/33
closing this one. please reopen if needed
