### ISSUE TITLE
Can't find docs referenced in Readme.md?

### ISSUE THREAD

**Issue by roschler** [ethereum/remixd#46]
Whenever I try to open one of the doc links referenced in the Readme.MD file, I see an error telling me the page doesn't exist.  Where are the docs?  For example:

http://remix.readthedocs.io/en/latest/tutorial_remixd_filesystem.html

Shows me this message:

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

**Comment by ninabreznik** [comment]
Hello, @roschler. How did you get to this tutorial, did you have it bookmarked?

It was renamed, so this broke the link. It is now available here http://remix.readthedocs.io/en/latest/tutorial_connect_remix_with_your_filesystem.html

**Comment by roschler** [comment]
@ninabreznik Click on the link found in the following text in the RemixD Readme.md page:

https://github.com/ethereum/remixd

_More details are explained in this **tutorial**._

**Comment by ninabreznik** [comment]
@roschler Thanks, maybe it would make sense to just rename it back, because who knows where else it is linked. Thanks a lot for this!

**Comment by ninabreznik** [comment]
Fixed!
