### ISSUE TITLE
An official tutorial is not working. Is it a bug?

### ISSUE THREAD

**Issue by wfcz10086** [ethereum/remixd#48]
link ：https://solidity.readthedocs.io/en/latest/solidity-by-example.html
![default](https://user-images.githubusercontent.com/31715243/42284609-a322ba22-7fdf-11e8-9064-70883e88d1bf.png)

I fill in the data  ["ABC","JPL"]
Report error：creation of Ballot errored: Error encoding arguments: Error: invalid bytes32 value (arg=undefined, type="string", value="ABC")
I'm sure the data is correct. Is this a bug? Or can developers run success

@yann300

**Comment by yann300** [comment]
the ABI encoder changed... it is needed now to input hex encoded string.
