### ISSUE TITLE
support truffle imports

### ISSUE THREAD

**Issue by maraoz** [ethereum/remixd#5]
First, thanks for creating this cool tool. 

Truffle-style imports (specifically, using npm-installed modules) are not working with `remixd`.
See: https://truffle.readthedocs.io/en/beta/getting_started/packages/

**Comment by yann300** [comment]
the PR is there https://github.com/ethereum/browser-solidity/pull/699 . just pull it if you want to use it now cause that might take long before being pushed to remix.ethereum.org

**Comment by maraoz** [comment]
awesome, thanks! ping @ajsantander

**Comment by ajsantander** [comment]
@yann300 thanks for pointing that out, however, your PR doesn't seem to do the trick

This is my setup:

-some-truffle-project
   - contracts
     - MyContract.sol <- (imports zeppelin-solidity/contracts/math/SafeMath.sol)
   - test
   - node_modules <- (zeppelin-solidity/contracts/math/SafeMath.sol in here)
   - truffle.js
   ...

I checked out yann300's browser-solidity "truffleImport" branch and ran browser-solidity locally, then pointed remixd to the "contracts" folder. Doesn't recognize the imports.

However, if I point remixd to "some-truffle-project" (i.e. the parent folder that contains node_modules), it works. But this also works with browser-solidity's "master" branch, which suggests that yann300's solution is not it.

Beyond that, this solution is not ideal because browser-solidity seems to hang for a while when first opening the project (because it has to read a lot of non-solidity files), and -since the sidebar doesn't scroll- there is no way in which I can see the imported contracts in the editor. Beats having to copy the imported dependencies locally tho.

I suggest solution in which remixd allows simlinks, if that is possible of course.

**Comment by yann300** [comment]
I see. so the easiest solution would be for now to have a .remixdignore ( https://github.com/ethereum/remixd/issues/7 ) . We'll then work for a long term solution. 
simlinks is possible but that will require more time.

**Comment by stefek99** [comment]
I'm using some OpenZeppelin code.

I thought that rather than copy-paste 10+files I can simply use `remixed`

For some reason does not work: https://youtu.be/t-xaCjRdVCQ

I believe my issue is the same as your issue.

Any workarounds?

*(previously included links are dead)*

**Comment by netpi** [comment]
@maraoz @ajsantander @stefek99 
My temporary solution is
```
npm install truffle-flattener -g

truffle-flattener myContractWithImport > out.sol
```
copy out.sol, paste to remix IDE 
: )

**Comment by ProphetDaniel** [comment]
I published a package for testing purposes in the meanwhile it is not merged to the master branch. 

[remixd-prophet](https://www.npmjs.com/package/remixd-prophet)

`npm install -g remixd-prophet`

Usage:
`remixd-prophet -s <shared folder>`

**Comment by yann300** [comment]
@ProphetDaniel that's great! we have a PR, remix-ide for that, but it get long to be merged..

Are you going to maintain that one in the long term?  if yes we could warn the user at startup that it is preferable to use `remixd-prophet` for Truffle. if no could we include the functionnality in remix too?
thanks for contributing!

**Comment by yann300** [comment]
just saw the pr ;)

**Comment by ProphetDaniel** [comment]
> Are you going to maintain that one in the long term?

I think we better work together and combine development efforts. 
I have no problem in maintaining it in the long term thought. 

Use my code fragment wherever needed @yann300.

**Comment by yann300** [comment]
@ProphetDaniel I worked a bit on that yesterday, thanks for pushing on this issue ;)

The PR is nice but I am not sure we should auto update the import ref like this..
Modifying the content without warning the user is a bit tricky and might be seen as a bug.

Here is a proposition:
I pushed a PR yesterday in the remix-ide repo which add a first support of `node_modules` and `installed_contracts` : https://github.com/ethereum/remix-ide/pull/1328 . That pr is also pushed to 
https://remix-alpha.ethereum.org
if that PR is not sufficient then we would merge yours and add an UI option in the settings for that.

could you please verify / review that `node_modules` import works ok on `remix-alpha.ethereum.org` (and using remixd)  ?

Thanks ;)

If you would like to put more effort in remixd (or remix broadly), please join https://gitter.im/ethereum/remix-dev , we would greatly appreciate

**Comment by ProphetDaniel** [comment]
@yann300 , perfect. It is working on remix-alpha.ethereum.org together with remixd. Great job everyone!

**Comment by MoMannn** [comment]
@yann300 I tried using alpa but doesn't work for me. This is the case I am trying: https://github.com/0xcert/ethereum-erc721

@ProphetDaniel Did you do the node_module imports the same way I did?

**Comment by yann300** [comment]
@MoMannn how are you importing the solidity file?

**Comment by yann300** [comment]
@MoMannn please could you give another try? a fix has been pushed

**Comment by MoMannn** [comment]
@yann300  It works now, thanks for the fix! :)

**Comment by MoMannn** [comment]
@yann300 is there any timeline when this will be available on the official channel: https://remix.ethereum.org/ ?

**Comment by yann300** [comment]
hopefully next week

**Comment by yann300** [comment]
that's in ;)

**Comment by ktimam** [comment]
Is this working on the latest (i tried it out on appVersion=0.7.7 and is working fine, doesn't seem to be working on the latest though)?
