### ISSUE TITLE
[ERR] URL Remix IDE instance has to be provided.

### ISSUE THREAD

**Issue by princesinha19** [ethereum/remixd#64]
I have installed remixd using command:-
`npm install -g remixd`

But when I am trying to share a folder using remixd then it gives error [ERR] URL Remix IDE instance has to be provided.

I am using command **remixd -s "directory_name"**.

**Comment by rajeshsubhankar** [comment]
You have to provide the remix-ide URL,
`remixd -s <shared folder> --remix-ide  <url>`

**Comment by crossoveranx** [comment]
Now when I'm using https://remix.ethereum.org to connect to my local instance, it consistently rejects it. This was not the case a few versions ago.

**Comment by princesinha19** [comment]
@rajeshsubhankar Thanks.

**Comment by creazy231** [comment]
@crossoveranx make sure run it like `remixd -s . --remix-ide "https://remix.ethereum.org"` and don't paste the url like `https://remix.ethereum.org/` the `/` made the difference for me
