### ISSUE TITLE
Connection from origin http://127.0.0.1:8080 rejected

### ISSUE THREAD

**Issue by superman285** [ethereum/remixd#71]
Hi excuse me, when I update the newest remixd ,I type "remixd --remix-ide http://127.0.0.1" in my folder's command line,I got the mistake"Connection from origin http://127.0.0.1:8080 rejected.". But the last remixd version I don't have this problem,can you help me please? thank you

**Comment by lamborcai** [comment]
Executing: npm install --global --production windows-build-tools and then
executing npm rebuild

I install passed,you can try it.

**Comment by gregorynicholas** [comment]
?

**Comment by ioedeveloper** [comment]
Use `remixd -s ./ --remix-ide http://127.0.0.1:8080`
