### ISSUE TITLE
Read Only Mode

### ISSUE THREAD

**Issue by skilesare** [ethereum/remixd#8]
My general workflow is that I use VS Code with truffle to edit my project and only fire up remix when I have a nasty compile error or I'm ready to deploy some contracts.  On a couple of occasions I've had VS Code and remixd step all over each other trying to save different version of a file.  Thanks to dropbox I was able to find the stuff that was erased.

It would be great to be able to run remixd in read only mode via a switch so that I know it isn't going to write back to my file if my cat jumps up on the keyboard while I have remix open.

**Comment by apuigsech** [comment]
I support this, is it will also protect my file from remix issues (It happens sometimes that you lost your work due remix issue).

**Comment by ajsantander** [comment]
+20 here
I am a Vim user and I would like to perform the text editing with vim, and use remix for everything else.

In general, an option to disable autosave would allow people to use their own text editor.

**Comment by yann300** [comment]
this change has been published, corresponding PR is not in remix.ethereum but in remix-alpha.ethereum.org
