### ISSUE TITLE
Websocket sendUTf(null)

### ISSUE THREAD

**Issue by mjobrien05** [ethereum/remixd#83]
This affects v0.1.8-alpha.9 (v0.1.8-alpha.7 works for me).

Running `remixd -s $PWD --remix-ide https://remix.ethereum.org &` I get the attached error.

![image](https://user-images.githubusercontent.com/1685524/65288025-20e3f400-dafa-11e9-9746-157d48bd74ab.png)

**Comment by Sotatek-PhuongNguyen** [comment]
Did you find the solution for this problem ?

**Comment by danforbes** [comment]
Getting the same problem
